parameters:
  configurationName: ''
  configurationParameters: ''
  loadOpCache: 'yes'
  xdebugConfigurationParameters: '--with-xdebug-compression'

jobs:
  - job: ${{ parameters.configurationName }}
    pool:
      vmImage: 'macos-14'
    steps:
    - template: brew.yml
    - template: php.yml
      parameters:
        phpVersion: ${{ parameters.phpVersion }}
        phpBranch: ${{ parameters.phpBranch }}
        configurationParameters: ${{ parameters.configurationParameters }}
    - script: |
        export PATH="/usr/local/bin:$PATH"
        phpize && ./configure ${{ parameters.xdebugConfigurationParameters }} && make clean && make all && sudo make install
      displayName: 'Compile Xdebug'
    - template: test.yml
      parameters:
        configurationName: ${{ parameters.configurationName }}
        loadOpCache: ${{ parameters.loadOpCache }}
    - template: test.yml
      parameters:
        configurationName: ${{ parameters.configurationName }}
        loadOpCache: ${{ parameters.loadOpCache }}
        runTestsName: 'Opcache'
        opCache: 'yes'
